FROM node:19.8.1-alpine3.17 AS build

WORKDIR /app
COPY package.json yarn.lock* ./
RUN yarn --frozen-lock
COPY . .
ENV VITE_SERVER_URL "http://localhost:5000/cv"
RUN [ "yarn", "build" ]

FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/dist .
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
