FROM node:19.8.1-alpine3.17 AS Build

WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

COPY package.json .
RUN pnpm i
COPY . .

ENTRYPOINT [ "pnpm", "build" ]

FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=Build /app/dist .
ENTRYPOINT ["nginx", "-g", "daemon off;"]
EXPOSE 80
