version: "3"
services:
  web:
    container_name: prod_web
    build:
      context: client
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - "80:80"

  backend:
    container_name: prod_backend
    build:
      context: server
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - ${SERVER_PORT}:5000
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ROOT=${SERVER_ROOT}
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Kathmandu
    volumes:
      - ${CV_FILTER_PATH}:/server/uploads
