services:
  dev_web:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    volumes:
      - ${DEV_CLIENT_SRC}:/app

  dev_backend:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ROOT=${SERVER_ROOT}
    volumes:
      - ${DEV_SERVER_SRC}:/server
      - ${CV_FILTER_PATH}:/server/uploads:ro
