version: "3"
services:
  web:
    container_name: filter_web
    build:
      context: client
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - "80:80"

  backend:
    container_name: filter_backend
    build:
      context: server
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - ${PORT}:5000
    environment:
      - PORT=${PORT}
      - SERVER_URL=${SERVER_URL}
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Kathmandu
    volumes:
      - ${CV_PATH}:/server/uploads
