version: "3"
services:
  dev_web:
    container_name: filter_dev_web
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    volumes:
      - ${CLIENT_SRC_PATH}:/app/src

  dev_backend:
    container_name: filter_dev_backend
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - ${PORT}:5000
    environment:
      - PORT=${PORT}
      - SERVER_URL=${SERVER_URL}
      - TZ=Asia/Kathmandu
    volumes:
      - ./server/src:/server/src:ro
      - ${CV_PATH}:/server/uploads:rw
