version: "3"
services:
  dev_web:
    container_name: dev_web
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    volumes:
      - ${DEV_CLIENT_SRC}:/app/src

  dev_backend:
    container_name: dev_backend
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:5000
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ROOT=${SERVER_ROOT}
    volumes:
      - ./server/src:/server/src:ro
      - ${CV_FILTER_PATH}:/server/uploads:rw
